"""Agregar tabla entity_types

Revision ID: 158a6b3b7a00
Revises: 972af8b23a5d
Create Date: 2026-07-18 16:07:48.748386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158a6b3b7a00'
down_revision = '972af8b23a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_types')
    # ### end Alembic commands ###
