"""Hacer purchase_date opcional en assets

Revision ID: 7c011242b158
Revises: 536c5461dc72
Create Date: 2026-07-20 18:17:52.320065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c011242b158'
down_revision = '536c5461dc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
