"""Agregar campo year a assets

Revision ID: 972af8b23a5d
Revises: 966a2620785e
Create Date: 2026-07-16 18:01:41.422505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972af8b23a5d'
down_revision = '966a2620785e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
